server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RestaurantDatabase
    driverClassName: org.postgresql.Driver
    username: karol
    password: admin
  jpa.hibernate.ddl-auto: create-drop
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true